package com.kilogram.backendcore.dto.request;

import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Payload for updating user profile details.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UpdateProfileRequest {

    @Size(min = 2, max = 50, message = "Display name must be between 2 and 50 characters")
    private String displayName;

    @Size(max = 150, message = "Bio cannot exceed 150 characters")
    private String bio;

    // Field to receive the image URL string generated by cloud storage (e.g., Cloudinary/S3)
    private String avatarUrl;
}