server:
  port: 8080

spring:
  application:
    name: kilogram-backend
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/kilogram_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: KilogramSuperSecretKeyForJwtGenerationDoNotShare2026!@#
    expiration-milliseconds: 86400000

cloudinary:
  cloud-name: dah2e3q3f
  api-key: 523155919872356
  api-secret: dvpOwhfDOEfPZllNMDuJ83gf084

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

